### ISSUE TITLE
Single channel image

### ISSUE THREAD

**Issue by samuelnapit** [zalandoresearch/spatial_gan#2]
I want to ask if this method can process a single channel image (like: grayscale). If it is possible, can I find out about the configuration? And whether this can make the process faster? Thank you

**Comment by nikjetchev** [comment]
You need a simple workaround for grayscale: just convert it to RGB with 3 identical channels, than run code as usual.

**Comment by samuelnapit** [comment]
Sorry before, I want to do research to speed up a method with RGB channel separation. Is that possible to do with SGAN? Thank you
