### ISSUE TITLE
unable to do anything with this code

### ISSUE THREAD

**Issue by josephlandau** [zalandoresearch/spatial_gan#3]
syntax errors, library inconsistencies and I have the feeling you do not care.

**Comment by nikjetchev** [comment]
Hi

sorry that you could not do anything with this code. It is indeed discontinued, and we have newer versions, both Lasagne and Pytorch https://github.com/zalandoresearch/psgan Hope they are helpful for you.

**Comment by josephlandau** [comment]
There is still a ton of errors in that work also, seriously dude.
